language: node_js
matrix:
  include:
    - node_js: "7"
    - node_js: "6"
    - node_js: "4"

script: "[[ $BABEL == true ]] && npm run test:babel || npm test"
after_success:
  - npm run travis-coverage
